language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t clubbruin/cb-frontend .

script:
    - docker run -e CI=true clubbruin/cb-frontend npm test

after_sucess:
    - docker build -t clubbruin/cb-frontend .
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push clubbruin/cb-frontend

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-west-1
    app: clubbruin
    env: clubbruin-dev
    bucket_name: elasticbeanstalk-us-west-1-573755250687
    bucket_path: clubbruin
    on:
        branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
        
